### ISSUE TITLE
yarn start启动后会出现 无样式内容闪烁问题

### ISSUE THREAD

**Issue by elivoa** [umijs/umi-example-ssr-with-egg#10]
刷新页面先出现所有文字，没有样式，然后再刷新出样式。请问这个问题怎么解决？
原来UMI工程build好后是不会闪烁的。

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi-example-ssr-with-egg/commit/aff2b87577d5033178ce38d59bbb9131e3bf3423
