### ISSUE TITLE
在本地自己的项目里运行prerender命令时会报一个语法错误

### ISSUE THREAD

**Issue by jimmywong123** [umijs/umi-example-ssr-with-egg#17]
不过在umi-example-ssr-with-egg里并没有观察到这个错误，不知道是不是那里配置错误了？
![image](https://user-images.githubusercontent.com/42126331/64019265-44ea9000-cb61-11e9-8f5e-6817f6410c80.png)

**Comment by ycjcl868** [comment]
antd 引 `antd/lib*`

**Comment by jimmywong123** [comment]
### 我在把依赖umi-plugin-react从1.4.2升级到1.9.19后，这个报错就消失了，不过又出现了另外一个报错。
![image](https://user-images.githubusercontent.com/42126331/64484806-03856f00-d24a-11e9-9cbc-e7986f2b662c.png)
下方是我的配置，大神可以帮我分析一下吗？

### **package.json**
{
  "name": "u_hc_web",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "dependencies": {
    "@babel/runtime": "^7.3.1",
    "ant-design-pro": "^2.2.1",
    "antd": "^3.16.3",
    "axios": "^0.18.0",
    "bizcharts": "^3.2.2",
    "bizcharts-plugin-slider": "^2.0.3",
    "classnames": "^2.2.6",
    "cross-env": "^5.2.1",
    "cross-storage": "^1.0.0",
    "dva": "^2.4.0",
    "egg": "^2.4.1",
    "egg-alinode": "^2.0.1",
    "egg-jwt": "^3.1.6",
    "egg-redis": "^2.3.0",
    "egg-scripts": "^2.5.1",
    "egg-view-assets": "^1.4.3",
    "egg-view-nunjucks": "^2.2.0",
    "enquire-js": "^0.2.1",
    "hash.js": "^1.1.5",
    "install": "^0.12.2",
    "koa-static": "^5.0.0",
    "lodash": "^4.17.10",
    "lodash-decorators": "^6.0.0",
    "memoize-one": "^4.0.0",
    "moment": "^2.24.0",
    "npm": "^6.7.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.4.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.2",
    "rc-animate": "^2.4.4",
    "react": "^16.5.1",
    "react-container-query": "^0.11.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-meta": "^3.0.0-beta.2",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.5.1",
    "react-fittext": "^1.0.0",
    "react-helmet": "^5.2.1",
    "react-highlight-words": "^0.16.0",
    "react-infinite-scroller": "^1.2.3",
    "react-intl-universal": "^1.15.0",
    "react-media": "^1.9.2",
    "react-router-dom": "^4.3.1",
    "react-virtualized": "^9.21.0",
    "resize-observer-polyfill": "^1.5.1",
    "ssr-polyfill": "^1.0.0",
    "u_egg_db_base": "^1.2.9",
    "u_egg_web_base": "0.0.5",
    "u_webant": "^1.2.13",
    "u_webant_base": "0.0.30",
    "umi_base_config": "0.0.6",
    "util_react_request": "0.0.1",
    "util_react_web": "0.0.15",
    "util_storage": "0.0.1"
  },
  "devDependencies": {
    "@umijs/plugin-prerender": "^1.4.2",
    "antd-pro-merge-less": "^0.1.0",
    "antd-theme-webpack-plugin": "^1.1.8",
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "babel-eslint": "^8.1.2",
    "babel-jest": "^23.6.0",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "egg-bin": "^4.3.7",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.15.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.8.0",
    "eslint": "^4.18.2",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-egg": "^7.0.0",
    "eslint-config-prettier": "^3.6.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-compat": "^2.6.2",
    "eslint-plugin-import": "^2.15.0",
    "eslint-plugin-jsx-a11y": "^6.2.0",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.12.4",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^23.6.0",
    "jest-cli": "^23.6.0",
    "less-vars-to-js": "^1.3.0",
    "mockjs": "^1.0.1-beta3",
    "redbox-react": "^1.5.0",
    "umi": "^2.9.3",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-react": "^1.9.19",
    "umi-utils": "^1.5.6"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "scripts": {
    "start": "egg-scripts start --daemon --title=u_hc_web --env prod",
    "stop": "egg-scripts stop --title=u_hc_web",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "build": "APP_ROOT=$PWD/app/web umi build",
    "prerender": "npm run start && cross-env UMI_ENV=prerender umi build && egg-scripts stop",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod",
    "sync": "./script/sync.js",
    "tt": "npm install --production && tar -zcvf ../u_hc_web.tgz . && scp ../u_hc_web.tgz root@120.79.243.235:/home/egg/u_hc_web",
    "m": "git checkout master && git merge --no-ff dev",
    "pi": "npm install --production",
    "di": "git checkout -b dev master && npm i && npm run dev",
    "jest": "jest ./app/web --coverage"
  },
  "ci": {
    "version": "8"
  },
  "jest": {
    "transform": {
      "^.+\\.js$": "babel-jest"
    },
    "moduleFileExtensions": [
      "js",
      "jsx"
    ],
    "moduleDirectories": [
      "node_modules"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/app/web/__mocks__/fileMock.js",
      "\\.(css|scss)$": "identity-obj-proxy"
    }
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "Thomas Lau",
  "license": "MIT"
}

### **egg config**
'use strict';

const path = require('path');
const fs = require('fs');

module.exports = appInfo => {
  const config = exports = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1540891018161_6566';

  config.middleware = [ 'serve', 'i18nHandler' ];

  config.view = {
    root: path.join(appInfo.baseDir, 'app/view'),
    mapping: {
      '.html': 'nunjucks',
    },
  };

  config.assets = {
    publicPath: '/public',
    devServer: {
      command: 'umi dev',
      port: 8000,
      env: {
        APP_ROOT: path.join(__dirname, '../app/web'),
        BROWSER: 'none',
        SOCKET_SERVER: 'http://127.0.0.1:8000',
      },
      debug: true,
    },
  };

  config.security = {
    csrf: false,
  };

  config.redis = {
    client: {
      host: process.env.EGG_REDIS_HOST || '127.0.0.1',
      port: process.env.EGG_REDIS_PORT || 6379,
      password: process.env.EGG_REDIS_PASSWORD || '',
      db: process.env.EGG_REDIS_DB || '0',
    },
  };

  config.alinode = {
    // 从 `Node.js 性能平台` 获取对应的接入参数
    // https://node.console.aliyun.com/
    appid: process.env.EGG_ALINODE_APPID || '78234',
    secret: process.env.EGG_ALINODE_SECRET || 'f79e84a74f3c3203f7d26273083dc84c12f5a6ab',
  };

  config.apiPath = 'http://127.0.0.1:7107';

  config.system = {
    appid: '8-bYDm_3',
    secret: 'K-A_9xd9tURAPsgY',
  };

  config.cluster = {
    listen: {
      port: 3103,
      hostname: '127.0.0.1',
      // path: '/var/run/egg.sock',
    },
  };

  config.debug = true;

  exports.siteFile = {
    '/favicon.ico': fs.readFileSync(path.join(appInfo.baseDir, 'app/web/src/assets/favicon.png')),
  };

  return config;
};

### **umi config**
// https://umijs.org/config/
// import pageRoutes from './router.config';
// import config from 'umi_base_config';
import path from 'path';
import webpackPlugin from './plugin.config';
import theme from './theme.config';

const config = {};
config.chainWebpack = webpackPlugin;
config.theme = theme;
config.proxy = {
  '/api/v1': {
    target: "http://127.0.0.1:7107",
    changeOrigin: true,
    pathRewrite: { "^/api/v1": "/api/v1" }
  },
}

config.extraBabelIncludes = [
  path.join(__dirname, '../../../node_modules/u_webant_base'),
  path.join(__dirname, '../../../node_modules/util_react_request'),
  path.join(__dirname, '../../../node_modules/util_react_web'),
  path.join(__dirname, '../../../node_modules/util_storage'),
  path.join(__dirname, '../../../node_modules/u_webant'),
  path.join(__dirname, '../../../node_modules/lrz'),
]

config.ssr = true;

config.autoprefixer = { flexbox: true };
config.es5ImcompatibleVersions = true;
config.treeShaking = true;
config.targets = {
  ie: 9,
};

config.define = {
  APP_TYPE: process.env.APP_TYPE || '',
};


config.ignoreMomentLocale = true; // 忽略 moment 的 locale 文件，用于减少尺寸。
config.lessLoaderOptions = {
  javascriptEnabled: true,
};
config.disableRedirectHoist = true;


config.cssnano = {
  mergeRules: false,
};

// extra configuration for egg
config.runtimePublicPath = true; // 值为 true 时使用 HTML 里指定的 window.publicPath。
config.hash = true;
config.outputPath = '../public';
// 配置后会生成 manifest.json，option 传给 https://www.npmjs.com/package/webpack-manifest-plugin。 比如：
config.manifest = {
  fileName: '../../../config/manifest.json',
  publicPath: '',
};
config.extraBabelPlugins = [
  [
    'import', {
      libraryName: 'u_webant',
      libraryDirectory: 'lib',
      style: true,
      camel2DashComponentName: false,
    },
  ],
];

export default config;

### **prerender config**
import path from 'path';

const config = {
  hash: true,
  outputPath: './site',
  plugins: [
    [
      'umi-plugin-react',
      {
        hd: true,
        locale: {
          baseNavigator: false,
        },
        antd: true,
        dva: {
          immer: true,
        },
        headScripts: [
          {
            content: 'window.USE_PRERENDER = true;',
          }
        ],
        // TODO, page router css leak
        dynamicImport: {
          webpackChunkName: true,
          loadingComponent: './components/PageLoading/index',
        },
        dll: {
          include: [ 'dva', 'dva/router', 'dva/saga', 'dva/fetch', 'antd/es' ],
          exclude: [ '@babel/runtime' ],
        },
      },
    ],
    ['@umijs/plugin-prerender', {
      runInMockContext: {
        // your server address, for prerender get data
        url: 'http://localhost:7107',
      }
    }],
  ],
};

export default config;

**Comment by iisbigfish** [comment]
umi的配置文件里添加这个，然后把ssr或者预渲染的相关依赖升级
extraBabelPlugins: [
    [require.resolve('babel-plugin-import'), { libraryName: "antd", style: 'less' }],
  ],

**Comment by ycjcl868** [comment]
在 `['umi-plugin-react', { antd: true }]` 时，SSR 会关闭 `babel-plugin-import`，默认走的是 `lib`

**Comment by jimmywong123** [comment]
在引入一些纯es6写法的依赖包，也会报这个错，现在的ssr是不支持es6写法的包吧？
