### ISSUE TITLE
not work on win10 OS

### ISSUE THREAD

**Issue by icarusysuper** [umijs/umi-example-ssr-with-egg#2]
![image](https://user-images.githubusercontent.com/3395277/59894515-6b7aa500-9413-11e9-82a5-178f92f3acb8.png)

should change `\` to `\\`

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/pull/2662, 等搭车发新版

**Comment by icarusysuper** [comment]
@ycjcl868 Thanks
