### ISSUE TITLE
ssr 嵌套路由 

### ISSUE THREAD

**Issue by iisbigfish** [umijs/umi-example-ssr-with-egg#21]
在二级页面的时候 getInitialProps 在客户端不执行。
路径为 '/first/:sec'

**Comment by ycjcl868** [comment]
我试试

**Comment by iisbigfish** [comment]
![image](https://user-images.githubusercontent.com/23730777/66899708-fff5bc80-f02d-11e9-9a4c-890159ca35be.png)
![image](https://user-images.githubusercontent.com/23730777/66899750-0e43d880-f02e-11e9-8e7a-fd9620bf82ae.png)
![image](https://user-images.githubusercontent.com/23730777/66899513-adb49b80-f02d-11e9-81b6-2b794f52e42f.png)
![image](https://user-images.githubusercontent.com/23730777/66899484-9c6b8f00-f02d-11e9-921d-6d92863895b9.png)
![image](https://user-images.githubusercontent.com/23730777/66899582-cf158780-f02d-11e9-813d-91d84fd6509e.png)
好像是执行了，但是数据没同步的样子。具体调用如图，在服务端上的有打印出来，但是在客户端的g_initialData 里丢失了。

**Comment by iisbigfish** [comment]
![image](https://user-images.githubusercontent.com/23730777/66901189-cf635200-f030-11e9-8637-9d7643983f78.png)
然后关于部分有个疑问。客户端渲染的时候的getInitialProps在最初的时候不执行？

**Comment by jimmywong123** [comment]
动态路由getInitialProps在perrender时不会调用，只在页面第一次加载时调用。
如果客户端数据丢失，有可能是因为在页面类外层又包裹了一层导致的。

**Comment by iisbigfish** [comment]
> 动态路由getInitialProps在perrender时不会调用，只在页面第一次加载时调用。
> 如果客户端数据丢失，有可能是因为在页面类外层又包裹了一层导致的。

好像不仅仅是因为这个，在saga里面put是异步不阻塞的。把put改成put.resolve(action)后就有了。
