### ISSUE TITLE
页面首次加载时有明显的迟滞感

### ISSUE THREAD

**Issue by jimmywong123** [umijs/umi-example-ssr-with-egg#22]
![image](https://user-images.githubusercontent.com/42126331/66973753-83b1b680-f0cb-11e9-83bc-c4d38bc23547.png)
在我的项目里这一点非常明显，在谷歌浏览器分析，第一次请求在服务器的等待时间已经达到了1.5s。
![image](https://user-images.githubusercontent.com/42126331/66973902-f327a600-f0cb-11e9-8f77-8a7bfc5fce32.png)
观察示例项目的等待时间并没有那么长，只有0.1s的等待时间。
实际项目会涉及到数据库访问和网络延时，而getInitialProps中又必须通过同步的方式加载数据，无法做到异步并发加载。这一点是否可能会在以后的改进中改善？

**Comment by ycjcl868** [comment]
主要是要优化 server render 渲染这层，会提供一个 [umi-server](https://github.com/umijs/umi/pull/3447)

**Comment by jimmywong123** [comment]
可以尽快提供关于这个示例的代码吗，感谢！
