### ISSUE TITLE
更新umi-server后，页面性能变得更差了

### ISSUE THREAD

**Issue by jimmywong123** [umijs/umi-example-ssr-with-egg#24]
观察测试案例服务端加载时间比之前增加了一倍。
在真实项目中，这个问题会更加严重，会直接导致页面卡住不动。
![image](https://user-images.githubusercontent.com/42126331/67264487-c5809980-f4dd-11e9-98b6-969d861eeb53.png)

**Comment by ycjcl868** [comment]
优化 umi-server ，umi-server 是最小功能可用的 SSR render

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/67928966-32d7ad00-fbf7-11e9-8ba7-918a5e9ccfbc.png)

可能是 [_log](https://github.com/umijs/umi-server/pull/17/files#diff-7733b9689015bcf5e2ba654b3517db3bL123) html 导致的性能下降，试了下 now，之前，是 600 ms，现在是 200 ms。

**Comment by ycjcl868** [comment]
更新最新的 umi-server 试试

**Comment by jimmywong123** [comment]
可能有所提升吧，我的页面打开速度由1～1.2s提升到了0.8～1s左右。
![image](https://user-images.githubusercontent.com/42126331/68012727-d4c5cb00-fcc5-11e9-84db-ffa067a66e8f.png)
这里的慢可能是有多方面原因导致的，我排查到了以下几方面的原因：
1：项目本身的sql语句较慢，我的其中一个查询需要1s才能返回，这个在加了缓存之后有所改善。
2：getInitialProps必须通过同步的方式取数据，在真实项目中往往会有多个请求，这样就必然会有一个队列等待的时间。
3，另外上次卡住不动的原因后来发现是因为在head中添加了`<script async src="https://www.googletagmanager.com/gtag/js?id=UA-56511619-1"></script>`，这个是我们公司要做谷歌广告分析的，在我做ssr之前是没有这种情况出现的。
4，可能就是umi-server本身编译的问题了。

除了这些问题，不得不说现在的ssr实在是有太多坑了。。。

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/68101695-e39cbf80-ff09-11e9-84a5-8ba9f9468699.png)

umi-server@1.1.3，这个 umijs/umi-server#21 PR，基本降到 200 - 500ms 以内

**Comment by jimmywong123** [comment]
很可惜更新后并没有什么提升，我在预渲染的时候加载了大量的中英文国际化在头文件里，是大量（估计有100～200kb左右的数据），有可能是这个原因导致的。
![image](https://user-images.githubusercontent.com/42126331/68103122-87896980-ff10-11e9-9072-f323dd82bc87.png)

**Comment by jimmywong123** [comment]
如果你能把测试案例的预渲染页面加载到500kb大小，也许你们就能发现问题了

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/69302019-28875c80-0c53-11ea-9b7a-4ad8c7af4481.png)
