### ISSUE TITLE
没有服务端渲染

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi-example-ssr-with-egg#9]
运行`npm run dev`之后，在浏览器上面看到了页面，但是返回的 index.html 为什么没有内容，感觉不是 ssr 而是 csr 的呢？

![image](https://user-images.githubusercontent.com/8522646/61620885-560fc980-aca4-11e9-9045-5c9331a3fe82.png)

**Comment by ycjcl868** [comment]
访问 localhost:7001
